### ISSUE TITLE
Adding an OnUpdate() which is called after each model update

### ISSUE THREAD

**Issue by 89pleasure** [Cities2Modding/Gooee#2]
I recognized it would be awesome to have virtual override void OnUpdate() which can be called in a controller which is triggered automatically after the model updates. Right now I setup a custom void with OnTrigger annotation for it, but that feels duplicated since I have to call it always after each change on a model in the jsx files.

**Comment by optimus-code** [comment]
There is now a method you can override in the controller called "OnModelUpdated" that is triggered on change.
